public class Hourly{
    public int Id { get; set; }
    public DateTime? date { get; set; }
    public int DewPointC { get; set; }
    public int DewPointF { get; set; }
    public int FeelsLikeC { get; set; }
    public int FeelsLikeF { get; set; }
    public int HeatIndexC { get; set; }
    public int HeatIndexF { get; set; }
    public int WindChillC { get; set; }
    public int WindChillF { get; set; }
    public int WindGustKmph { get; set; }
    public int WindGustMiles { get; set; }
    public int chanceoffog { get; set; }
    public int chanceoffrost { get; set; }
    public int chanceofhightemp { get; set; }
    public int chanceofovercast { get; set; }
    public int chanceofrain { get; set; }
    public int chanceofremdry { get; set; }
    public int chanceofsnow { get; set; }
    public int chanceofsunshine { get; set; }
    public int chanceofthunder { get; set; }
    public int chanceofwindy { get; set; }
    public int cloudcover { get; set; }
    public float diffRad { get; set; }
    public int humidity { get; set; }
    public float precipInches { get; set; }
    public float precipMM { get; set; }
    public int pressure { get; set; }
    public int pressureInches { get; set; }
    public float shortRad { get; set; }
    public int tempC { get; set; }
    public int tempF { get; set; }
    public int time { get; set; }
    public int uvIndex { get; set; }
    public int visibility { get; set; }
    public int visibilityMiles { get; set; }
    public int weatherCode { get; set; }
    public string? winddir16Point { get; set; }
    public int winddirDegree { get; set; }
    public int windspeedKmph { get; set; }
    public int windspeedMiles { get; set; }
    public int avgtempC { get; set; }
    public int avgtempF { get; set; }
    public int maxtempC { get; set; }
    public int maxtempF { get; set; }
    public int mintempC { get; set; }
    public int mintempF { get; set; }
    public float sunHour { get; set; }
    public float totalSnow_cm { get; set; }
    public DateTime insertDate { get; set; }
    public DateTime lastUpdateDate { get; set; }
    public string? city {get; set;}
}